export const ingredients = [
  {
    name: 'Salt',
    category: 'seasoning or additive',
    gluten_free: true,
    vege: true,
    vegan: true,
  },
  {
    name: 'Pepper',
    category: 'seasoning or additive',
    gluten_free: true,
    vege: true,
    vegan: true,
  },
  {
    name: 'Olive oil',
    category: 'other',
    gluten_free: true,
    vege: true,
    vegan: true,
  },
  {
    name: 'Garlic',
    category: 'other',
    gluten_free: true,
    vege: true,
    vegan: true,
  },
  {
    name: 'Onion',
    category: 'other',
    gluten_free: true,
    vege: true,
    vegan: true,
  },
  {
    name: 'Butter',
    category: 'animal product',
    gluten_free: true,
    vege: true,
    vegan: false,
  },
  {
    name: 'Eggs',
    category: 'animal product',
    gluten_free: true,
    vege: true,
    vegan: false,
  },
  {
    name: 'Milk',
    category: 'animal product',
    gluten_free: true,
    vege: true,
    vegan: false,
  },
  {
    name: 'Flour',
    category: 'grain or flour',
    gluten_free: false,
    vege: true,
    vegan: true,
  },
  {
    name: 'Sugar',
    category: 'sweetener or fruit',
    gluten_free: true,
    vege: true,
    vegan: true,
  },
  {
    name: 'Chicken',
    category: 'animal product',
    gluten_free: true,
    vege: false,
    vegan: false,
  },
  {
    name: 'Beef',
    category: 'animal product',
    gluten_free: true,
    vege: false,
    vegan: false,
  },
  {
    name: 'Pork',
    category: 'animal product',
    gluten_free: true,
    vege: false,
    vegan: false,
  },
  {
    name: 'Tomatoes',
    category: 'vegetable or fruit',
    gluten_free: true,
    vege: true,
    vegan: true,
  },
  {
    name: 'Carrots',
    category: 'vegetable or fruit',
    gluten_free: true,
    vege: true,
    vegan: true,
  },
  {
    name: 'Potatoes',
    category: 'vegetable or fruit',
    gluten_free: true,
    vege: true,
    vegan: true,
  },
  {
    name: 'Bell peppers',
    category: 'vegetable or fruit',
    gluten_free: true,
    vege: true,
    vegan: true,
  },
  {
    name: 'Mushrooms',
    category: 'vegetable or fruit',
    gluten_free: true,
    vege: true,
    vegan: true,
  },
  {
    name: 'Lemon',
    category: 'vegetable or fruit',
    gluten_free: true,
    vege: true,
    vegan: true,
  },
  {
    name: 'Cheese',
    category: 'animal product',
    gluten_free: true,
    vege: true,
    vegan: false,
  },
  {
    name: 'Basil',
    category: 'herb or spice',
    gluten_free: true,
    vege: true,
    vegan: true,
  },
  {
    name: 'Oregano',
    category: 'herb or spice',
    gluten_free: true,
    vege: true,
    vegan: true,
  },
  {
    name: 'Parsley',
    category: 'herb or spice',
    gluten_free: true,
    vege: true,
    vegan: true,
  },
  {
    name: 'Thyme',
    category: 'herb or spice',
    gluten_free: true,
    vege: true,
    vegan: true,
  },
  {
    name: 'Bay leaves',
    category: 'herb or spice',
    gluten_free: true,
    vege: true,
    vegan: true,
  },
  {
    name: 'Soy sauce',
    category: 'condiment',
    gluten_free: false,
    vege: true,
    vegan: true,
  },
  {
    name: 'Rice',
    category: 'grain or flour',
    gluten_free: true,
    vege: true,
    vegan: true,
  },
  {
    name: 'Pasta',
    category: 'grain or flour',
    gluten_free: false,
    vege: true,
    vegan: true,
  },
  {
    name: 'Vinegar',
    category: 'seasoning or additive',
    gluten_free: true,
    vege: true,
    vegan: true,
  },
  {
    name: 'Baking powder',
    category: 'seasoning or additive',
    gluten_free: true,
    vege: true,
    vegan: true,
  },
  {
    name: 'Baking soda',
    category: 'seasoning or additive',
    gluten_free: true,
    vege: true,
    vegan: true,
  },
  {
    name: 'Cinnamon',
    category: 'other',
    gluten_free: true,
    vege: true,
    vegan: true,
  },
  {
    name: 'Nutmeg',
    category: 'other',
    gluten_free: true,
    vege: true,
    vegan: true,
  },
  {
    name: 'Ginger',
    category: 'other',
    gluten_free: true,
    vege: true,
    vegan: true,
  },
  {
    name: 'Chili powder',
    category: 'other',
    gluten_free: true,
    vege: true,
    vegan: true,
  },
  {
    name: 'Cumin',
    category: 'other',
    gluten_free: true,
    vege: true,
    vegan: true,
  },
  {
    name: 'Paprika',
    category: 'other',
    gluten_free: true,
    vege: true,
    vegan: true,
  },
  {
    name: 'Honey',
    category: 'sweetener or fruit',
    gluten_free: true,
    vege: true,
    vegan: false,
  },
  {
    name: 'Vanilla extract',
    category: 'seasoning or additive',
    gluten_free: true,
    vege: true,
    vegan: true,
  },
  {
    name: 'Spinach',
    category: 'vegetable or fruit',
    gluten_free: true,
    vege: true,
    vegan: true,
  },
  {
    name: 'Zucchini',
    category: 'vegetable or fruit',
    gluten_free: true,
    vege: true,
    vegan: true,
  },
  {
    name: 'Broccoli',
    category: 'vegetable or fruit',
    gluten_free: true,
    vege: true,
    vegan: true,
  },
  {
    name: 'Corn',
    category: 'vegetable or fruit',
    gluten_free: true,
    vege: true,
    vegan: true,
  },
  {
    name: 'Lettuce',
    category: 'vegetable or fruit',
    gluten_free: true,
    vege: true,
    vegan: true,
  },
  {
    name: 'Mayonnaise',
    category: 'condiment',
    gluten_free: true,
    vege: true,
    vegan: false,
  },
  {
    name: 'Mustard',
    category: 'condiment',
    gluten_free: true,
    vege: true,
    vegan: true,
  },
  {
    name: 'Ketchup',
    category: 'condiment',
    gluten_free: true,
    vege: true,
    vegan: true,
  },
  {
    name: 'Cream',
    category: 'animal product',
    gluten_free: true,
    vege: true,
    vegan: false,
  },
  {
    name: 'Yogurt',
    category: 'animal product',
    gluten_free: true,
    vege: true,
    vegan: false,
  },
  {
    name: 'Bread',
    category: 'other',
    gluten_free: false,
    vege: true,
    vegan: true,
  },
  {
    name: 'Rice noodles',
    category: 'grain or flour',
    gluten_free: true,
    vege: true,
    vegan: true,
  },
  {
    name: 'Gluten-free pasta',
    category: 'grain or flour',
    gluten_free: true,
    vege: true,
    vegan: true,
  },
  {
    name: 'Almond milk',
    category: 'dairy alternative',
    gluten_free: true,
    vege: true,
    vegan: true,
  },
  {
    name: 'Coconut milk',
    category: 'dairy alternative',
    gluten_free: true,
    vege: true,
    vegan: true,
  },
  {
    name: 'Oat milk (gluten-free certified)',
    category: 'dairy alternative',
    gluten_free: true,
    vege: true,
    vegan: true,
  },
  {
    name: 'Rice flour',
    category: 'grain or flour',
    gluten_free: true,
    vege: true,
    vegan: true,
  },
  {
    name: 'Almond flour',
    category: 'grain or flour',
    gluten_free: true,
    vege: true,
    vegan: true,
  },
  {
    name: 'Coconut flour',
    category: 'grain or flour',
    gluten_free: true,
    vege: true,
    vegan: true,
  },
  {
    name: 'Chickpea flour',
    category: 'grain or flour',
    gluten_free: true,
    vege: true,
    vegan: true,
  },
  {
    name: 'Tapioca starch',
    category: 'grain or flour',
    gluten_free: true,
    vege: true,
    vegan: true,
  },
  {
    name: 'Arrowroot powder',
    category: 'other',
    gluten_free: true,
    vege: true,
    vegan: true,
  },
  {
    name: 'Cornstarch',
    category: 'grain or flour',
    gluten_free: true,
    vege: true,
    vegan: true,
  },
  {
    name: 'Gluten-free oats',
    category: 'grain or flour',
    gluten_free: true,
    vege: true,
    vegan: true,
  },
  {
    name: 'Quinoa',
    category: 'other',
    gluten_free: true,
    vege: true,
    vegan: true,
  },
  {
    name: 'Buckwheat',
    category: 'other',
    gluten_free: true,
    vege: true,
    vegan: true,
  },
  {
    name: 'Millet',
    category: 'other',
    gluten_free: true,
    vege: true,
    vegan: true,
  },
  {
    name: 'Sweet potatoes',
    category: 'other',
    gluten_free: true,
    vege: true,
    vegan: true,
  },
  {
    name: 'Avocado',
    category: 'vegetable or fruit',
    gluten_free: true,
    vege: true,
    vegan: true,
  },
  {
    name: 'Chia seeds',
    category: 'seeds',
    gluten_free: true,
    vege: true,
    vegan: true,
  },
  {
    name: 'Flax seeds',
    category: 'seeds',
    gluten_free: true,
    vege: true,
    vegan: true,
  },
  {
    name: 'Hemp seeds',
    category: 'seeds',
    gluten_free: true,
    vege: true,
    vegan: true,
  },
  {
    name: 'Maple syrup',
    category: 'sweetener or fruit',
    gluten_free: true,
    vege: true,
    vegan: true,
  },
  {
    name: 'Coconut oil',
    category: 'other',
    gluten_free: true,
    vege: true,
    vegan: true,
  },
  {
    name: 'Nutritional yeast',
    category: 'seasoning or additive',
    gluten_free: true,
    vege: true,
    vegan: true,
  },
  {
    name: 'Tahini',
    category: 'other',
    gluten_free: true,
    vege: true,
    vegan: true,
  },
  {
    name: 'Sunflower butter',
    category: 'other',
    gluten_free: true,
    vege: true,
    vegan: true,
  },
  {
    name: 'Cashew cream',
    category: 'dairy alternative',
    gluten_free: true,
    vege: true,
    vegan: true,
  },
  {
    name: 'Tofu',
    category: 'legume or plant protein',
    gluten_free: true,
    vege: true,
    vegan: true,
  },
  {
    name: 'Tempeh (gluten-free)',
    category: 'legume or plant protein',
    gluten_free: true,
    vege: true,
    vegan: true,
  },
  {
    name: 'Lentils',
    category: 'legume or plant protein',
    gluten_free: true,
    vege: true,
    vegan: true,
  },
  {
    name: 'Black beans',
    category: 'legume or plant protein',
    gluten_free: true,
    vege: true,
    vegan: true,
  },
  {
    name: 'Kidney beans',
    category: 'legume or plant protein',
    gluten_free: true,
    vege: true,
    vegan: true,
  },
  {
    name: 'Canned coconut cream',
    category: 'dairy alternative',
    gluten_free: true,
    vege: true,
    vegan: true,
  },
  {
    name: 'Vegetable broth (gluten-free)',
    category: 'other',
    gluten_free: true,
    vege: true,
    vegan: true,
  },
  {
    name: 'Fresh herbs',
    category: 'herb or spice',
    gluten_free: true,
    vege: true,
    vegan: true,
  },
  {
    name: 'Lime',
    category: 'vegetable or fruit',
    gluten_free: true,
    vege: true,
    vegan: true,
  },
  {
    name: 'Pumpkin',
    category: 'vegetable or fruit',
    gluten_free: true,
    vege: true,
    vegan: true,
  },
  {
    name: 'Zucchini noodles (zoodles)',
    category: 'grain or flour',
    gluten_free: true,
    vege: true,
    vegan: true,
  },
  {
    name: 'Cauliflower rice',
    category: 'grain or flour',
    gluten_free: true,
    vege: true,
    vegan: true,
  },
  {
    name: 'Seaweed (nori, wakame)',
    category: 'vegetable or fruit',
    gluten_free: true,
    vege: true,
    vegan: true,
  },
  {
    name: 'Tamari (gluten-free soy sauce)',
    category: 'condiment',
    gluten_free: true,
    vege: true,
    vegan: true,
  },
  {
    name: 'Miso paste (gluten-free)',
    category: 'condiment',
    gluten_free: true,
    vege: true,
    vegan: true,
  },
  {
    name: 'Dates',
    category: 'sweetener or fruit',
    gluten_free: true,
    vege: true,
    vegan: true,
  },
  {
    name: 'Bananas',
    category: 'sweetener or fruit',
    gluten_free: true,
    vege: true,
    vegan: true,
  },
  {
    name: 'Berries',
    category: 'vegetable or fruit',
    gluten_free: true,
    vege: true,
    vegan: true,
  },
  {
    name: 'Unsweetened applesauce',
    category: 'sweetener or fruit',
    gluten_free: true,
    vege: true,
    vegan: true,
  },
  {
    name: 'Cacao powder (pure)',
    category: 'seasoning or additive',
    gluten_free: true,
    vege: true,
    vegan: true,
  },
  {
    name: 'Dark chocolate (dairy-free)',
    category: 'other',
    gluten_free: true,
    vege: true,
    vegan: true,
  },
  {
    name: 'Plant-based yogurt (e.g., coconut or almond)',
    category: 'dairy alternative',
    gluten_free: true,
    vege: true,
    vegan: true,
  },
];
